Portion of frontend for replies
LapisHusky/mppclone pull request #149
Opened 2023-05-19 01:12 UTC by Vapor9473

Just needs links to replies, clicking on the links, detection for if the server can access the message id (Which I have no clue how to do any of these).

2023-05-22 06:38 UTC, lithiumjs requested changes
Also, more indentation issues.

2023-05-22 06:38 UTC, lithiumjs commented on client/script.js
> +      startDmReply: function (part, id, arr) {
Check if the participant is present before starting a DM.

2023-05-22 06:38 UTC, lithiumjs commented on client/script.js
> +          if (gIsReplying && !gIsDming) {
I would much rather do that with nested `if` statements.

2023-05-22 06:38 UTC, lithiumjs commented on client/script.js
> +        var liString = `<li><span id="msg-${msg.id}">`;
There's no need for `<span>` here, you can assign the ID to the `<li>` element directly.

2023-05-22 06:38 UTC, lithiumjs commented on client/script.js
> +          li.find(".replyLink").text(`➦ ${(repliedMsg?.a?.length > 5 ? repliedMsg?.a?.substring(0, 5) + "..." : repliedMsg?.a?.substring(0, 5)) ?? "Unknown Message"}`);
5 seems arbitrary and too short. Also, include the username.

2023-05-22 06:38 UTC, lithiumjs commented on client/script.js
> +              $(`#msg-${repliedMsg?.id}`).css({"background": "#8B8000", "transition": "background 0.5s"});
Weird color, IMO. Maybe we can do something with the original author's color?

2023-05-22 06:38 UTC, lithiumjs commented on client/script.js
> +        li.find(`.id2`).css({"cursor": "pointer"});
No need for this, you already set that in the CSS file.

2023-05-22 20:31 UTC, Vapor9473 commented on client/script.js
> +              $(`#msg-${repliedMsg?.id}`).css({"background": "#8B8000", "transition": "background 0.5s"});
Original author?

2023-05-22 21:04 UTC, Nitsua0615 commented on client/script.js
> +              $(`#msg-${repliedMsg?.id}`).css({"background": "#8B8000", "transition": "background 0.5s"});
Original author - Person who sent the message that is being replied to

2023-05-23 01:37 UTC, Vapor9473 commented on client/script.js
> +          li.find(".replyLink").text(`➦ ${(repliedMsg?.a?.length > 5 ? repliedMsg?.a?.substring(0, 5) + "..." : repliedMsg?.a?.substring(0, 5)) ?? "Unknown Message"}`);
Included name, changed substring to length from 0,5 to 0,10

2023-05-23 02:01 UTC, Vapor9473 commented on client/script.js
> +      startDmReply: function (part, id, arr) {
Included. I don't know if it would be smart to add something that allows the user to reply regardless, but instead of it being inside of a DM, it replies publicly.

2023-05-24 06:50 UTC, merged